apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: aharon-rossano-pipeline-from-scratch-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: aharon-rossano-pipeline-from-scratch-pipeline
  workspaces:
    - name: pipeline-shared-data
      persistentVolumeClaim:
        claimName: aharon-rossano-live-pvc2