apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: aharon-rossano-pipeline-from-scratch-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: aharon-rossano-pipeline-from-scratch-pipeline-run-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: aharon-rossano-pipeline-from-scratch-pipeline
        workspaces:
          - name: pipeline-shared-data
            persistentVolumeClaim:
              claimName: aharon-rossano-pvc
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: aharon-rossano-pipeline-from-scratch-pipeline-triggerbinding
spec:
  params:
    - name: namespace
      value: aharon-rossano-pipeline-from-scratch
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: gitrepositoryname
      value: $(body.repository.name)
